creation_rules:
  # vm-control-01 secrets — encrypted with vm-control-01 age key
  - path_regex: secrets/vm-control-01/.*\.yaml$
    age: >-
      age1gl7leqyhfvyaflc7t5cktjq4k75qwnd4kyk79td03lkpxxr35fps03lpuf

  # mtto-server secrets — host age key (generated 2026-04-25 during recovery).
  - path_regex: secrets/mtto-server/.*\.yaml$
    age: >-
      age1hwpzl06ekt0fagugzneqt0rtcg852px8tvaxy4lp7mfuw89x5f6s4qavu8
